### PR TITLE
Fix typescript error

### PR DESCRIPTION
**Pull request by chris--jones**
#32

### CODE REVIEW

**Comment by zzarcon** [comment]
This is awesome, thanks a lot @chris--jones !

**Comment by zzarcon** [comment]
Oh, seems like the tests are failing, can you please update them accordingly with the new change?

**Comment by chris--jones** [comment]
> 
> 
> Oh, seems like the tests are failing, can you please update them accordingly with the new change?

Oops, I'll see if I can fix it.

Ironically I couldn't get the tests to run due to that also throwing errors for me, but I see the changes needed in the snapshot.

**Comment by zzarcon** [comment]
Merged, thanks @chris--jones ! 🚀

**Pull request merged**
